# Generated by Django 4.2.7 on 2023-11-04 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TAlumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_alumno', models.CharField(max_length=50)),
                ('apellido_alumno', models.CharField(max_length=50)),
                ('dni_alumno', models.CharField(max_length=8, unique=True)),
                ('fecha_nacimiento_alumno', models.DateField()),
                ('grado_alumno', models.IntegerField()),
                ('genero_alumno', models.IntegerField()),
                ('estado_alumno', models.IntegerField()),
            ],
            options={
                'permissions': (('mispermisos_view_talumno', 'Puede ver las alumnos'), ('mispermisos_add_talumno', 'Puede agregar alumnos'), ('mispermisos_change_talumno', 'Puede editar alumnos'), ('mispermisos_delete_talumno', 'Puede eliminar alumnos')),
            },
        ),
        migrations.CreateModel(
            name='TCarrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_carrera', models.CharField(max_length=100)),
                ('estado_carrera', models.IntegerField()),
            ],
            options={
                'permissions': (('mispermisos_view_tcarrera', 'Puede ver las carreras'), ('mispermisos_add_tcarrera', 'Puede agregar carreras'), ('mispermisos_change_tcarrera', 'Puede editar carreras'), ('mispermisos_delete_tcarrera', 'Puede eliminar carreras')),
            },
        ),
        migrations.CreateModel(
            name='TCategoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('imagen_categoria', models.CharField(blank=True, max_length=450, null=True)),
                ('nombre_categoria', models.CharField(max_length=50)),
                ('estado_categoria', models.IntegerField()),
                ('pregunta_categoria', models.CharField(max_length=45)),
            ],
            options={
                'permissions': (('mispermisos_view_tcategoria', 'Puede ver las categorias'), ('mispermisos_add_tcategoria', 'Puede agregar categorias'), ('mispermisos_change_tcategoria', 'Puede editar categorias'), ('mispermisos_delete_tcategoria', 'Puede eliminar categorias')),
            },
        ),
        migrations.CreateModel(
            name='TComunicado',
            fields=[
                ('id_comunicado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comunicado', models.CharField(blank=True, max_length=50, null=True)),
                ('img_comunicado', models.ImageField(blank=True, null=True, upload_to='comunicados')),
                ('fecha_comunicado', models.DateField(blank=True, null=True)),
                ('estado_comunicado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'permissions': (('mispermisos_view_tcomunicado', 'Puede ver los comunicados'), ('mispermisos_add_tcomunicado', 'Puede agregar comunicados'), ('mispermisos_change_tcomunicado', 'Puede editar comunicados'), ('mispermisos_delete_tcomunicado', 'Puede eliminar comunicados')),
            },
        ),
        migrations.CreateModel(
            name='TConfiguracion',
            fields=[
                ('id_configuracion', models.AutoField(primary_key=True, serialize=False)),
                ('telefono_configuracion', models.CharField(blank=True, max_length=12, null=True)),
                ('direccion_configuracion', models.CharField(blank=True, max_length=50, null=True)),
                ('correo_configuracion', models.CharField(blank=True, max_length=50, null=True)),
                ('manual_configuracion', models.FileField(blank=True, null=True, upload_to='manual/')),
                ('img_firma_configuracion', models.ImageField(blank=True, null=True, upload_to='firma/')),
                ('datos_psicologo_configuracion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'permissions': (('mispermisos_view_tconfiguracion', 'Puede ver las configuraciones'), ('mispermisos_change_tconfiguracion', 'Puede editar configuraciones')),
            },
        ),
        migrations.CreateModel(
            name='TEncuesta',
            fields=[
                ('id_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_encuesta', models.DateField(blank=True, null=True)),
                ('hora_encuesta', models.TimeField(blank=True, null=True)),
                ('estado_encuesta', models.IntegerField(blank=True, null=True)),
                ('id_alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.DO_NOTHING, to='panel_admin.talumno')),
            ],
            options={
                'permissions': (('mispermisos_view_tencuesta', 'Puede ver las encuestas'), ('mispermisos_add_tencuesta', 'Puede agregar encuestas'), ('mispermisos_change_tencuesta', 'Puede editar encuestas'), ('mispermisos_delete_tencuesta', 'Puede eliminar encuestas')),
            },
        ),
        migrations.CreateModel(
            name='TFicha_alumno',
            fields=[
                ('id_ficha_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ficha_alumno', models.DateField()),
                ('hora_ficha_alumno', models.TimeField()),
                ('id_alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.DO_NOTHING, to='panel_admin.talumno')),
            ],
        ),
        migrations.CreateModel(
            name='TPregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pregunta', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_pregunta', models.IntegerField(blank=True, null=True)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.DO_NOTHING, to='panel_admin.tcategoria')),
            ],
            options={
                'permissions': (('mispermisos_view_tpregunta', 'Puede ver las preguntas'), ('mispermisos_add_tpregunta', 'Puede agregar preguntas'), ('mispermisos_change_tpregunta', 'Puede editar preguntas'), ('mispermisos_delete_tpregunta', 'Puede eliminar preguntas')),
            },
        ),
        migrations.CreateModel(
            name='TRedSocial',
            fields=[
                ('id_red_social', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_red_social', models.CharField(blank=True, max_length=20, null=True)),
                ('url_red_social', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TVocacion',
            fields=[
                ('id_vocacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_vocacion', models.CharField(max_length=100)),
                ('start_baremos_vocacion', models.IntegerField()),
                ('intervalo_baremos_vocacion', models.IntegerField()),
                ('estado_vocacion', models.IntegerField()),
            ],
            options={
                'permissions': (('mispermisos_view_tvocacion', 'Puede ver las vocaciones'), ('mispermisos_add_tvocacion', 'Puede agregar vocaciones'), ('mispermisos_change_tvocacion', 'Puede editar vocaciones'), ('mispermisos_delete_tvocacion', 'Puede eliminar vocaciones')),
            },
        ),
        migrations.CreateModel(
            name='TUsuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('apellido_usuario', models.CharField(max_length=50)),
                ('dni_usuario', models.CharField(max_length=8)),
                ('estado_usuario', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('mispermisos_view_tusuario', 'Puede ver los usuarios'), ('mispermisos_add_tusuario', 'Puede agregar usuarios'), ('mispermisos_change_tusuario', 'Puede editar usuarios'), ('mispermisos_delete_tusuario', 'Puede eliminar usuarios')),
            },
        ),
        migrations.CreateModel(
            name='TRespuesta',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('valor_respuesta', models.IntegerField()),
                ('id_encuesta', models.ForeignKey(db_column='id_encuesta', on_delete=django.db.models.deletion.DO_NOTHING, to='panel_admin.tencuesta')),
                ('id_pregunta', models.ForeignKey(db_column='id_pregunta', on_delete=django.db.models.deletion.DO_NOTHING, to='panel_admin.tpregunta')),
            ],
            options={
                'permissions': (('mispermisos_view_trespuesta', 'Puede ver las respuestas'),),
            },
        ),
        migrations.AddField(
            model_name='tpregunta',
            name='id_vocacion',
            field=models.ForeignKey(db_column='id_vocacion', on_delete=django.db.models.deletion.DO_NOTHING, to='panel_admin.tvocacion'),
        ),
        migrations.CreateModel(
            name='TFicha_alumno_detalle',
            fields=[
                ('id_ficha_alumno_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('id_carrera', models.ForeignKey(db_column='id_carrera', on_delete=django.db.models.deletion.DO_NOTHING, to='panel_admin.tcarrera')),
                ('id_ficha_alumno', models.ForeignKey(db_column='id_ficha_alumno', on_delete=django.db.models.deletion.DO_NOTHING, to='panel_admin.tficha_alumno')),
                ('id_vocacion', models.ForeignKey(db_column='id_vocacion', on_delete=django.db.models.deletion.DO_NOTHING, to='panel_admin.tvocacion')),
            ],
        ),
        migrations.CreateModel(
            name='TColegio',
            fields=[
                ('id_colegio', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_colegio', models.CharField(max_length=50, unique=True)),
                ('nombre_colegio', models.CharField(max_length=50)),
                ('telefono_colegio', models.CharField(blank=True, max_length=12, null=True)),
                ('direccion_colegio', models.CharField(blank=True, max_length=30, null=True)),
                ('logo_colegio', models.ImageField(blank=True, null=True, upload_to='logos_colegio/')),
                ('estado_colegio', models.IntegerField()),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('mispermisos_view_tcolegio', 'Puede ver las colegios'), ('mispermisos_add_tcolegio', 'Puede agregar colegios'), ('mispermisos_change_tcolegio', 'Puede editar colegios'), ('mispermisos_delete_tcolegio', 'Puede eliminar colegios')),
            },
        ),
        migrations.AddField(
            model_name='tcarrera',
            name='id_vocacion',
            field=models.ForeignKey(db_column='id_vocacion', on_delete=django.db.models.deletion.DO_NOTHING, to='panel_admin.tvocacion'),
        ),
        migrations.AddField(
            model_name='talumno',
            name='id_colegio',
            field=models.ForeignKey(db_column='id_colegio', on_delete=django.db.models.deletion.DO_NOTHING, to='panel_admin.tcolegio'),
        ),
    ]
